### ISSUE TITLE
Sprites - Synth-Graft

### ISSUE THREAD

**Issue by harryob** [cmss13-devs/cm-roadmap#16]
Make sprites for synth-graft - a version of surgical line that heals burn damage only.

**Comment by BeagleGaming1** [comment]
The synth-graft sprites are in this PR already https://github.com/cmss13-devs/cmss13/pull/2874

**Comment by ItsVyzo** [comment]
Merged [#5200](https://github.com/cmss13-devs/cmss13/pull/5200)
