### ISSUE TITLE
OWLF integration

### ISSUE THREAD

**Issue by ghost** [cmss13-devs/cm-roadmap#39]
Sprites are required for the majority of it. 
We have uniforms, hoods, vests, gas masks.
We will require guns and more detail is always welcome.
![Image](https://user-images.githubusercontent.com/8919187/226440401-88c3cd9b-4b2e-40ee-b232-ea7d2307045e.png)

DM Morrow#1453 for the above sprites.

We'll need to code in the above sprites.
An ERT will need to be set up as well as equipment sets.

We want an OWLF ERT to respond when a predator body or gear is brought aboard and catalogued in research for intel points.

Alongside this we want to integrate thwei further into research in some way. Gear should give intel points. Incentives for marines to bring predator bodies and gear shipside to study should be expanded on given the OOC known risk of predators boarding to retrieve gear/bodies.

**Comment by Drulikar** [comment]
Some sprites added in https://github.com/cmss13-devs/cmss13/pull/2877 but not all sprites are in

- Likely needs to be implemented as a mid round ERT if it is a predator round
